/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_my_encrypt_EncryptUtils */

#ifndef _Included_com_my_encrypt_EncryptUtils
#define _Included_com_my_encrypt_EncryptUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_my_encrypt_EncryptUtils
 * Method:    getKeyValue
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_my_encrypt_EncryptUtils_getKeyValue
  (JNIEnv *, jclass);

/*
 * Class:     com_my_encrypt_EncryptUtils
 * Method:    getIv
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_my_encrypt_EncryptUtils_getIv
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
