/* DO NOT EDIT THIS FILE - it is machine generated
 *
 * 到下面这个目录
 * MyProject\myproject\build\intermediates\classes\debug
 *
 * 执行
 * javah -jni com.my.project.update.bsdiff.DiffUtils
 *
 * 生成该文件
 *
 * */

#include <jni.h>
/* Header for class com_my_project_update_bsdiff_DiffUtils */

#ifndef _Included_com_my_project_update_bsdiff_DiffUtils
#define _Included_com_my_project_update_bsdiff_DiffUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_my_project_update_bsdiff_DiffUtils
 * Method:    genDiff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_my_project_update_bsdiff_DiffUtils_genDiff
        (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
